name: CI & Deploy (Render)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest with coverage
        env:
          PYTHONPATH: "${{ github.workspace }}/HoraActual"
        run: |
          pytest --cov=app --cov-report=term-missing -q
      - name: Generate HTML coverage (artifact)
        if: always()
        env:
          PYTHONPATH: "${{ github.workspace }}/HoraActual"
        run: |
          pytest --cov=app --cov-report=html -q
      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

  deploy:
    needs: tests
    if: ${{ github.event_name == 'push' && needs.tests.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy via webhook
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$HOOK" ]; then
            echo "Missing secret RENDER_DEPLOY_HOOK"; exit 1;
          fi
          curl -fsS -X POST "$HOOK"
          echo "Deploy triggered in Render ✅"
